# Generated by Django 4.2 on 2025-05-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0008_alter_cartitem_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('is_Primary', models.BooleanField(default=False)),
            ],
        ),
    ]
