# Generated by Django 4.2 on 2025-05-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0010_productimage_product_alter_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='is_Primary',
            new_name='is_primary',
        ),
    ]
